aluno/urls.py
from django.urls import path

from . import views

app_name = 'aluno'

urlpatterns = [
    path('lista', views.listar, name='listar'),
    path('cadastra', views.cadastrar, name='cadastrar'),
]

instrutor/urls.py
from django.urls import path

from . import views

app_name = 'instrutor'

urlpatterns = [
    path('listaInstrutor/', views.listarInstrutor, name='listarInstrutor'),
    path('cadastraInstrutor/', views.CadastrarInstrutor, name='CadastrarInstrutor'),
    path('cadastroInstrutor/', views.CadastroInstrutor, name='CadastroInstrutor'),
]

setup/urls.py
from django.contrib import admin
from django.urls import include, path

from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', TemplateView.as_view(template_name='escola.html')),

    path('', include("tiposdeatividade.urls") ),
    path('aluno/', include("aluno.urls", namespace='aluno')),
    path('', include("instrutor.urls")),
    path('', include("titulo.urls")),
    path('', include("turma.urls")),
    path('', include("utilitarios.urls"))
]

#urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tiposdeatividade/urls.py
from django.urls import path

from . import views

app_name = 'tiposdeatividade'

urlpatterns = [
    path('listaTiposAtividade/', views.listarTiposAtividade, name='listarTiposAtividade'),
    path('cadastraTiposAtividade/', views.cadastraTiposAtividade, name='cadastraTiposAtividade'),
    path('cadastroTiposAtividade/', views.cadastroTiposAtividade, name='cadastroTiposAtividade'),
    # path('excluir/<int:codigo>', views.excluir, name='ecluir_atividade'),
    ]

titulo/urls.py
from django.urls import path

from . import views

app_name = 'titulo'

urlpatterns = [
    path('listaTitulo/', views.listarTitulo, name='listarTitulo'),
    path('cadastrarTitulo/', views.cadastrarTitulo, name='cadastrarTitulo'),
    path('cadastroTitulo/', views.cadastroTitulo, name='cadastroTitulo'),
    path('excluir/<int:codigo>', views.excluir, name='excluir_titulo'),
    path('carregar_titulo/<int:codigo>', views.carregar_titulo, name='carregar_titulo'),
    path('atualizar_titulo/', views.atualizar, name='atualizar_titulo'),
]

turma/urls.py
from django.urls import path

from . import views

app_name = 'turma'

urlpatterns = [
    path('listaTurma', views.listarTurma, name='listarTurma'),
    path('cadastraTurma', views.cadastrarTurma, name='cadastrarTurma'),
    path('registraAusencia', views.registroAusencia, name='registroAusencia')
]

utilitarios/urls.py
from django.urls import path
from utilitarios import utils
from . import views

app_name = 'contatos'

urlpatterns = [
    path('carga/', views.popular_bd, name='popular'),
    path('contato/', views.contato, name='contato'),
]

utilitarios/models.py
from django.db import models

# Create your models here.

utilitarios/views.py
from django.shortcuts import HttpResponse, render, redirect
from utilitarios import utils

# Create your views here.

def contato(request):
    return render(request, 'utilitarios/contato.html')

def popular_bd(request):
    utils.truncar_tabelas()
    utils.popular_tiposdeatividade()
    utils.popular_titulo()
    utils.popular_aluno()
    utils.popular_instrutor()
    utils.popular_turma()
    return redirect('/')

utilitarios/templates/utilitarios/contato.html
{% extends "base_template.html" %}

{% block title %}
        <title>Django - Exercícios</title>
{% endblock %}

{% block menu %}
<div class="collapse navbar-collapse justify-content-end" id="mynavbar">
    <div class="navbar-nav">
        <a href="/" class="nav-link">Início</a>
        <a href="{% url 'tiposdeatividade:cadastroTiposAtividade' %}" class="nav-link">Tipos de Atividade</a>
        <a href="{% url 'titulo:cadastroTitulo' %}" class="nav-link">Títulos</a>
        <a href="{% url 'aluno:cadastrar' %}" class="nav-link">Alunos</a>
        <a href="{% url 'instrutor:listarInstrutor' %}" class="nav-link">Instrutor</a>
        <a href="{% url 'turma:cadastrarTurma' %}" class="nav-link">Turmas</a>
    </div>
</div>
</nav>
{% endblock %}

{% block titulo_pagina %}
<main class="container m-2 w-75 mx-auto minha-fonte">
        
    <div class= "row">
        <div class="col text-center m-0">
            <h2 class="mt-2 mb-0 my-h2">Fale conosco</h2>
        </div>                    
    </div>

    <form name="frmContato" id="idFrmContato" action="#" method="POST" class="my-label-color-purple">

        <div class="form-row mt-4">
                <div class="form-group col-md-6">
                    <label for="idNome">Nome</label>
                    <input class="form-control" type="text" name="nome" id="idNome" maxlength="70" placeholder="Informe o seu Nome" required>
                </div>
            
                <div class="form-group col-md-6">
                        <label for="idUltimoNome">Último Nome</label>
                        <input class="form-control" type="text" name="ultimoNome" id="idUltimoNome" maxlength="70" placeholder="Informe o seu último Nome" required>
                </div>
        </div>

        <div class="form-group">
            <label for="idEmail">E-mail</label>
            <input class="form-control" type="email" name="email" id="idEmail" maxlength="100" placeholder="Informe o seu E-mail" required>
        </div>          
        
        <div class="form-group">
            <label for="idTelefone">Telefone</label>
            <input class="form-control" type="tel" name="telefone" id="idTelefone" placeholder="Informe o seu Telefone"  
                   pattern="(\(?[0-9]{2}\)?\s)?([0-9]{4}\-[0-9]{4})" required>
        </div>

        <fildset class="form-group">

            <div class="row">
                <legend class="col-form-label pt-0 col-md-2">Gênero</legend>

                <div class="col-md-10">
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="radio" name="genero" value="F" id="idGeneroF">
                        <label class="form-check-label" for="idGeneroF">Feminino</label>
                    </div>
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="radio" name="genero" value="M" id="idGeneroF">
                        <label class="form-check-label" for="idGeneroM">Masculino</label>
                    </div>
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="radio" name="genero" value="O" id="idGeneroO">
                        <label class="form-check-label" for="idGeneroO">Outros</label>
                    </div>
                </div>    
            </div>
        </fildset>

        <div class="form-group">
            <label for="idAssunto">Assunto</label>
            <select class="form-control" name="assunto" id="idAssunto" required>
                <option value="0" selected>Selecione...</option>
                <option value="E">Elogio</option>
                <option value="C">Crítica</option>
                <option value="S">Solicitação</option>
                <option value="O">Outros</option>
            </select>
        </div>
        
        <div class="form-group">
            <label for="idMensagem">Mensagem</label>
            <textarea class="form-control" rows="10" col="200" id="idMensagem" name="mensagem" class="myTextArea" placeholder="Preencha com a mensagem desejada" required></textarea>
        </div>

        <div class="form-group text-center">
            <input type="reset" value="Limpar"  class="btn btn-primary btn-md">
            <input type="submit" value="Enviar" class="btn btn-primary btn-md">
        </div>
    </form>
</main>

{% endblock %}















<!DOCTYPE html>
<html lang="pt-br">

<head>
    <title>Django - Exercícios</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- define e insere um favicon no documento HTML -->
    <link href="./img/python.ico" rel="shortcut icon">

    <!-- versao gratuita do Font Awesome icons-->
    <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" crossorigin="anonymous"></script>

    <!-- Bootstrap -->
    <!-- insira este conteudo aqui que representa o CSS do Bootstrap -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
        integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

    <!-- Google  icons -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <link href="../css/meu-estilo.css" rel="stylesheet">
</head>

<body>

    <!-- seu codigo comeca aqui -->

    <!-- container bootstrap -->
    <header class="container px-0">

        <nav class="navbar navbar-expand-lg navbar-light bg-light px-0">

            <!-- logo -->
            <div>
                <a class="navbar-brand mx-auto">
                    <img src="../img/python_64.png">
                </a>
            </div>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mynavbar"
                aria-controls="conteudoNavbarSuportado" aria-expanded="false" aria-label="Navegação Alternativa">
                Menu <span class="navbar-toggler-icon"></span>
            </button>

            <!-- menu -->
            <div class="collapse navbar-collapse justify-content-end" id="mynavbar">
                <div class="navbar-nav">
                    <a href="../escola.html" class="nav-link">Início</a>
                    <a href="../tipoatividade/cadastroTiposAtividade.html" class="nav-link">Tipos de Atividade</a>
                    <a href="../titulo/cadastroTitulos.html" class="nav-link">Títulos</a>
                    <a href="../aluno/cadastroAluno.html" class="nav-link">Alunos</a>
                    <a href="../instrutor/cadastroInstrutor.html" class="nav-link">Instrutor</a>
                    <a href="../turma/cadastroTurma.html" class="nav-link">Turmas</a>
                </div>
            </div>
        </nav>
    </header>

    

    <footer class="container text-center">
        <div class="row border-top border-primary bg-light">
            <div class="col font text-primary copyright">
                <p>&copy; Copyright Pmg Web</p>
            </div>
        </div>
    </footer>

    <!-- seu codigo termina aqui -->

    <!-- Bootstrap -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous">
    </script>

</body>

</html>